---
engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 40

languages:
   Ruby: false
   JavaScript: false
   PHP: true
   Python: false

exclude_paths:
  - tests/**/*